MedLib/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    url(r'^', include('main.urls')),
    url(r'^admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



app_name = 'main'
#This sets application namespace to diffretiate urls of different apps.

urlpatterns = [
    #url for home-page:
    url(r'^$', views.index, name='index'),
    url(r'^aboutus$', views.aboutus, name='aboutus'),
    url(r'^gallery$', views.gallery, name='gallery'),
    url(r'^contactus$', views.contactus, name='contactus'),
    #url for login-page:
    url(r'^login$', views.login, name='login'),
    #url for signup-page:

    #url to log in a user:
    url(r'^log_req$', views.logInReq, name='login_req'),

    #url for create-user:
    url(r'^register_user$', views.register, name='register_user'),

    #url for logged-in:
    #url(r'(?P<pk>[0-9]+)/logged_in/$',views.LoggedIn.as_view(),name='loggedin'),

    #url for logout:
    url(r'^logout$', views.logout, name='logout'),

    #url to search a topic:
    url(r'^search$', views.search, name='search'),

    url(r'^search1$', views.search1, name='search1'),

    #url to search a topic:
    url(r'^search_checkup$', views.search_checkup, name='search_checkup'),


    url(r'^quest$', views.quest, name='quest'),

    url(r'^doctors$', views.doc_list, name='doc_list'),

    url(r'^question$', views.question, name='question'),

    url(r'^ajaxreq',views.ajaxreq,name='ajaxreq'),
    url(r'^basicsymptoms/$',views.basicsymptoms,name='basicsymptoms'),
    url(r'^reports$',views.reports,name='reports'),
    url(r'^checknow',views.checknow,name='checknow'),


]

main/models.py
from django.db import models

class Users(models.Model):
    email = models.CharField(max_length=120, unique=True)
    pwd= models.CharField(max_length=80)





    #no_of_topics=models.IntegerField(default=0)
    #type_user=models.IntegerField(default=0) #simple=0 org=1
    #def __str__(self):
    #    return self

class History(models.Model):
    email = models.CharField(max_length=120)
    dis_name = models.CharField(max_length=120)
    dis_severity = models.CharField(max_length=120)
    dis_probname = models.CharField(max_length=120)
    dis_hint = models.CharField(max_length=120)
    dis_time = models.CharField(max_length=120)


"""
class Topic(models.Model):
    #tags = models.ForeignKey(Tag, on_delete = models.CASCADE)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    topic_text = models.CharField(max_length=250)
    topic_desc=models.CharField(max_length=700,default="")
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.topic_text


class Tag(models.Model):
    tag_name= models.CharField(max_length=50)
    tag_desc=models.CharField(max_length=500,default="")
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    def __str__(self):
        return self.tag_name

class Opinion(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    opinion_text=models.CharField(max_length=500)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)
    foragainst=models.IntegerField(default=0) #for=1 against=0
    def __str__(self):
        return self.user.user_name
"""

main/forms.py
from django import forms

class SignupForm(forms.Form):
    email = forms.CharField(max_length=120)
    pwd = forms.CharField(max_length=80)


class LoginForm(forms.Form):
    email=forms.CharField(max_length = 80)
    pwd= forms.CharField(max_length=80)

"""
class AddTopicForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)
    topic_desc=forms.CharField(max_length = 700)
    tag_text=forms.CharField(max_length = 250)

class AddOpinionForm(forms.Form):
    opinion_text=forms.CharField(max_length = 500)
    topic = forms.CharField(max_length = 5)
"""

class SearchForm(forms.Form):
    topic_text=forms.CharField(max_length = 250)
    #symptom=forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,required=False)

main/views.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist  # This may be used instead of Users.DoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from .medget import medget
from django.views import generic
from django.db import IntegrityError
import re
from main import medplace
from django.urls import reverse
# for older versoins of Django use:
# from django.core.urlresolvers import reverse
import ast
import datetime
import time

from .models import Users, History
from main.forms import SignupForm, LoginForm, SearchForm  # ,AddTopicForm,AddOpinionForm,

ob = medget()
j = []


def index(request):
        return render(request, 'Temp/index.html')

def aboutus(request):
        return render(request, 'Temp/about.html')

def gallery(request):
        return render(request, 'Temp/gallery.html')

def contactus(request):
        return render(request,'Temp/contact.html')

def checknow(request):
    if request.session.has_key('user_id'):
        uid = request.session['user_id']
        try:
            user = Users.objects.get(pk=uid)
            hist = []
            hist.extend(History.objects.filter(email=user.email).values('dis_name', 'dis_severity', 'dis_time'))
            # return HttpResponse(hist)
            return render(request, 'Temp/symptomdash.html', {'user_id': user, 'history': hist})
        except Users.DoesNotExist:
            return HttpResponse("UserName not found")
    else:
        return render(request, 'Temp/signupform.html')

def reports(request):
    if request.session.has_key('user_id'):

        uid = request.session['user_id']
        try:
            user = Users.objects.get(pk=uid)
            hist = []
            hist.extend(History.objects.filter(email=user.email).values('dis_name', 'dis_severity', 'dis_time'))
            # return HttpResponse(hist)
            return render(request, 'Temp/reports.html', {'user_id': user, 'history': hist})
        except Users.DoesNotExist:
            return HttpResponse("UserName not found")


def login(request):
    return HttpResponseRedirect(reverse('main:checknow'))




def search_checkup(request):
    return render(request, 'Temp/search_checkup.html')




def search(request):
    if request.method == 'POST':
        topic = SearchForm(request.POST)
        if topic.is_valid():

            # t=Topic.objects.get(topic_text=topic.cleaned_data.get('topic_text'))
            top_li = Topic.objects.all()
            li = []
            for t in top_li:
                if re.search(topic.cleaned_data.get('topic_text'), t.topic_text, re.IGNORECASE):
                    li.append(t)
            if request.session.has_key('user_id'):
                uid = request.session['user_id']
                user = Users.objects.get(pk=uid)
                return render(request, 'Temp/searchresults.html', {'user_id': user, "list": li})
            else:
                return render(request, 'Temp/searchresultL.html', {"list": li})
        else:
            return HttpResponse("Form not valid")
    else:
        return HttpResponse("not POST")


def search1(request):
        print(request)
        topic = SearchForm(request.POST, initial={"topic_text": "c"})
        if topic.is_valid():
            sim_str = topic.cleaned_data.get('topic_text')
            checklist = sim_str.split(",")
            # checklist = topic.cleaned_data.get('symptom')
            try:
                checklist.append(request.POST['symptom1'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom2'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom3'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom4'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom5'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom6'])
            except:
                pass
            try:
                checklist.append(request.POST['symptom7'])
            except:
                pass
            # return HttpResponse(checklist)


            li = ob.search_symptoms(checklist)

            l = len(li)
            return render(request, 'Temp/request2.html', {"list": li, "len": l})


            # return HttpResponse((' ').join(li))
            # t=Topic.objects.get(topic_text=topic.cleaned_data.get('topic_text'))

        else:
            
            return HttpResponse(topic.errors)



def register(request):
    try:
        if request.method == 'POST':
            
            em=str(request.POST['email'])
            pw=str(request.POST['pwd'])
            p = Users(email=em,pwd=pw)
            p.save()
            return HttpResponseRedirect(reverse('main:login'))
    except IntegrityError:
        return HttpResponse("You are already registered.")




def logInReq(request):
    if request.method == 'POST':
        log = LoginForm(request.POST)
        if log.is_valid():
            try:
                em=log.cleaned_data.get('email')
                pw=log.cleaned_data.get('pwd')
                print(em)
                print(pw)
                user = Users.objects.get(email = em,pwd = pw)
                request.session['user_id'] = user.id
                # return render(request,'Temp/dashboard.html')
                return HttpResponseRedirect(reverse('main:checknow'))
            except Users.DoesNotExist:
                return HttpResponse("WRONG USERNAME OR PASSWORD")


"""
class LoggedIn(generic.DetailView):
    model = Users
    template_name = 'Temp/logged.html'
    context_object_name = 'user_id'
"""


def quest(request):

    global ob
    if request.method == 'POST':
        l = request.POST['len']
        checklist = []
        print("11111111111")
        for i in range(int(l)):
            try:
                checklist.append(request.POST['symptom' + str(i)])
            except:
                print("22222222")
                pass
        # return HttpResponse(checklist)
        if request.session.has_key('user_id'):
            uid = request.session['user_id']
            try:
                print("3333333")
                user = Users.objects.get(pk=uid)
            except ObjectDoesNotExist:
                HttpResponse("Object not found")
            print("444444")
            age = request.session['age']
            sex = request.session['sex']
            print (age)
            print("55555")
            ob.get_data(sex, age)
            lis = []
            for i in checklist:
                dic = {}
                dic['id'] = i
                dic['status'] = 'present'
                lis.append(dic)
                dic = None

            # ob.add_symptoms(lis)
            request.session['lis'] = lis
            print("44455555555555555555555555")
            return HttpResponseRedirect(reverse('main:question'))
            # return HttpResponse(a)
            # ob.get_questions()


def question(request):

    ob = medget()
    # global j
    # j +=1
    i = []
    if request.session.has_key('lis'):
        i = request.session['lis']
        try:
            del request.session['lis']
        except:
            pass
        print("3rererer")
        age = request.session['age']
        sex = request.session['sex']
        ob.get_data(sex, age)
        ob.add_symptoms(i)
        request.session['a']=i
        a = ob.get_question()
        return render(request, 'Temp/myquestion.html', {"ques_dict": a})
        # return HttpResponse(a)
    elif not ob.check_risk(request):
        i = {}
        # id = request.POST.get('id')
        if request.POST.get('yes'):
            i['id'] = str(request.POST['option'])
            i['status'] = 'present'
        elif request.POST.get('no'):
            i['id'] = str(request.POST['option'])
            i['status'] = 'absent'
        elif request.POST.get('dont'):
            i['id'] = str(request.POST['option'])
            i['status'] = 'unknown'
        try:
            a=request.session['a']
        except:
            a=[]
        a.append(i)
        request.session['a']=a
        age = request.session['age']
        sex = request.session['sex']
        ob.get_data(sex, age)
        ob.add_symptoms(a)
        a = ob.get_question()
        # j = i
        return render(request, 'Temp/myquestion.html', {"ques_dict": a})
    else:
        result = {}
        uid = request.session['user_id']
        user = Users.objects.get(pk=uid)
        result = ob.get_result(request)
        History(
            email=user.email,
            dis_name=result['name'],
            dis_severity=result['severity'],
            dis_probname="",
            dis_hint=result['hint'],
            dis_time=str(datetime.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d %H:%M:%S')),
        ).save()
        return render(request, 'Temp/myresult.html', {"result": result})


def doc_list(request):
    #location = request.POST['location']
    #loc_dict = ast.literal_eval(location)
    loc_dict1 = {}
    try:
        loc_dict1['lat'] = request.COOKIES.get('latitude')
        print("in try1")
    except:
        loc_dict1['lat'] = loc_dict['latitude'] #request.COOKIES.get('latitude')
        print("in catch 1")
    try:
        loc_dict1['lng'] = request.COOKIES.get('longitude')
        print("in try 2")
    except:
        loc_dict1['lng'] = loc_dict['longitude'] #request.COOKIES.get('longitude')
        print("in catch 2")
    doctor_type = request.POST['doctor_type']
    print("                         ")
    print(loc_dict1['lat'])
    print(loc_dict1['lng'])
    print("                                       ")
    doctor = doctor_type.split()
    doctor_search = doctor[-2] + doctor[-1]
    plac = medplace.get_places(lat_lng=loc_dict1, doctor_type=doctor_search)

main/templates/Temp/contact.html

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>{%load static%}
<html>
<head>
<title>Contact</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Medicinal Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="applisalonion/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{%static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{% static 'css/slider.css' %}">
<script src="{%static 'js/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{%static 'js/easing.js' %}"></script>
<!--/web-font-->
<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
<!--/script-->
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
				});
			});
</script>
</head>
<body>
<!--start-home-->
<div class="main-header" id="house">
			<div class="header-strip">
			   <div class="container">
				<p class="location"><span class="glyphicon glyphicon-envelope" aria-hidden="true" ></span> <a href="mailto:info@example.com">shubhamjuneja11@gmail.com</a></p>

				<div class="clearfix"></div>
			</div>
			</div>
			<div class="header-middle">
			  <div class="header-search">
			   <form action="#" method="post">



				<div class="clearfix"></div>
			</form>
		</div>
	</div>
		<!--header-top-->
<div class="header-top">
			  <div class="container">
					 <nav class="navbar navbar-default">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
					  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					  </button>
						<div class="logo">
							<h1><a class="navbar-brand" href="{%url 'main:index' %}">e<span>M</span>edicare  <img src="{%static 'img/logo.png'%}" alt=" " /></a></h1>
						</div>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
						  <div class="top-menu">
							<nav class="menu menu--francisco">
									<ul class="nav navbar-nav menu__list">
										<li class="menu__item"><a href="{%url 'main:index' %}" class="menu__link"><span class="menu__helper">Home</span></a></li>
										<li class="menu__item"><a href="{%url 'main:aboutus' %}" class="menu__link"><span class="menu__helper">About Us</span></a></li>
								
										<li class="menu__item menu__item--current"><a href="{%url 'main:contactus' %}" class="menu__link"><span class="menu__helper">Contact Us</span></a></li>
										<li>
										<a href="login"><button type="button" class="btn btn-success" style="display:block;padding:10px;margin-top:20px;margin-left:30px;" > Start Check-up</button></a>
										</li>
									</ul>
								</nav>
							</div>
					</div>
					<!-- /.navbar-collapse -->
				</nav>

			   <div class="clearfix"></div>
			</div>
	</div>
</div>
<!--//header-top-->
 <!-- //Line Slider -->
		<div class="top_banner two">
			<div class="container">
			       <div class="sub-hd-inner">
						<h3 class="tittle">CONTACT <span>US</span></h3>
					</div>
			</div>
		</div>
	<!--/contact-->
		<div class="contact-top">
		    <div class="container">
				  <div class="contact-text">
				    <div class="con-text">
					  <p > shubhamjuneja11@gmail.com</p>
					  <p> amit.usict@gmail.com</p>
					  <p>pranav.handoo@gmail.com</p>
				   
					 <h6> USICT,Delhi,India</h6>
				  </div>
				 </div>
				
			</div>
		</div>
	<!--//contact-->

	  <!--/start-footer-section-->
	<div class="footer-section">
				<div class="container">
					<div class="footer-grids wow bounceIn animated" data-wow-delay="0.4s">
						<div class="col-md-3 footer-grid">
						<h4>The <span>Team</span></h4>
						<div class="border2"></div>
						  <p>We are a team of 3 developers. We all are passionate about social welfare and see technology as a powerful tool for the betterment of the society.</p>
						  <p class="sub">SHUBHAM JUNEJA</p>
						  <p>         -Lead, eMedicare</p>
						</div>
						<div class="col-md-3 footer-grid tags col-md-offset-6">
								<h4>The <span>Tags</span></h4>
								<div class="border2"></div>
							<ul class="tag">
								<li><a href="#">Diagnosis</a></li>
								<li><a href="#">Symptoms</a></li>
								<li><a href="#">Health</a></li>
								<li><a href="#">Doctor</a></li>
								<li><a href="#">Medicine</a></li>
								<li><a href="#">Treatment</a></li>
								<li><a href="#">Hospital</a></li>
								<li><a href="#">Analysis</a></li>
								<li><a href="#">Treatment</a></li>
								<li><a href="#">Medical</a></li>
								<li><a href="#">Anti-Biotics</a></li>
							</ul>
						</div>
						
						
						<div class="clearfix"></div>
					</div>
			</div>
		</div>
		<!--start-smooth-scrolling-->
						<script type="text/javascript">
									$(document).ready(function() {
										/*
										var defaults = {
								  			containerID: 'toTop', // fading element id
											containerHoverID: 'toTopHover', // fading element hover id
											scrollSpeed: 1200,
											easingType: 'linear'
								 		};
										*/

										$().UItoTop({ easingType: 'easeOutQuart' });

									});
								</script>
								<!--end-smooth-scrolling-->
		<a href="#house" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	<script src="{% static 'js/bootstrap.js' %}"></script>

</body>
</html>

main/templates/Temp/request0.html
<form id="form">

    Gender
    <div id="sex">
  <input type="radio" name="gender" value="male" checked> Male
  <input type="radio" name="gender" value="female"> Female<br>
</div>
<br><br>
Age
    <input type="number" name="quantity" id="quantity" min="1" max="120">
    </form>
    <br><br>
<div>

               <button type="button" class="btn btn-success btn-md nextbutton" id="nextbutton" onclick="myfun()">Next</button>
            </div>

main/templates/Temp/signupform.html
<!DOCTYPE html>{% load static %}
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="UTF-8" />
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
       <title>Signin</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
        <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
        <meta name="author" content="Codrops" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/signupformstyle.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />




<link href="{%static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- Custom Theme files -->
<link href="{%static 'css/style.css'%}" rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{%static 'css/slider.css'%}">
<script src="{%static 'js/jquery-1.11.1.min.js'%}"></script>
<script type="text/javascript" src="{%static 'js/move-top.js' %}"></script>
<script type="text/javascript" src="{%static 'js/easing.js'%}"></script>
<!--/web-font-->
<link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
<!--/script-->





    </head>
    <body>
   
    <div class="main-header" id="house">
            <div class="header-strip">
               <div class="container">
                <p class="location"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <a href="mailto:info@example.com">shubhamjuneja11@gmail.com</a></p>

                <div class="clearfix"></div>
            </div>
            </div>
            <div class="header-middle">
              <div class="header-search">
               <form action="#" method="post">



                <div class="clearfix"></div>
            </form>
        </div>
    </div>

                <div class="header-top">
              <div class="container">
                     <nav class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                        <div class="logo">
                            <h1><a class="navbar-brand" href="{%url 'main:index' %}">e<span>M</span>edicare  <img src="{%static 'img/logo.png'%}" alt=" " /></a></h1>
                        </div>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                          <div class="top-menu">
                            <nav class="menu menu--francisco">
                                    <ul class="nav navbar-nav menu__list">
                                        <li class="menu__item menu__item--current"><a href="{%url 'main:index' %}" class="menu__link"><span class="menu__helper">Home</span></a></li>
                                        <li class="menu__item"><a href="{%url 'main:aboutus' %}" class="menu__link"><span class="menu__helper">About Us</span></a></li>
                                
                                        <li class="menu__item"><a href="{%url 'main:contactus' %}" class="menu__link"><span class="menu__helper">Contact Us</span></a></li>
                                    
                                    </ul>
                                </nav>
                            </div>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>

               <div class="clearfix"></div>
            </div>
    </div>
            
            <section>
                <div id="container_demo" >
                    <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  --> 
                    <a class="hiddenanchor" id="toregister"></a>
                    <a class="hiddenanchor" id="tologin"></a>
                    <div id="wrapper">
                        <div id="login" class="animate form">
                            <form  method="POST" action="{% url 'main:login_req' %}" autocomplete="on" >

                                {% csrf_token %}
                              
                                <h1>Log in</h1>
                                <p>
                                    <label for="username" class="uname" data-icon="u" > Your email</label>
                                    <input id="username" name="email" required="required" type="text" placeholder="mymail@mail.com"/>
                                </p>
                                <p>
                                    <label for="password" class="youpasswd" data-icon="p"> Your password </label>
                                    <input id="password" name="pwd" required="required" type="password" placeholder="eg. X8df!90EO" />
                                </p>
                                <p class="keeplogin">

								</p>
                                <p class="login button">
                                    <input type="submit" value="Login" />
								</p>
                                <p class="change_link">
									Not a member yet ?
									<a href="#toregister" class="to_register" onclick="changetitletosignup()">Join us</a>
								</p>
                            </form>

                        </div>

                        <div id="register" class="animate form">

                            <form  method="POST" action="{% url 'main:register_user' %}" autocomplete="on">
                                {% csrf_token %}
 
                                </script>
                                <h1> Sign up </h1>

                                <p>

                                  <label for="emailsignup" class="youmail" data-icon="e" > Your email</label>
                                    <input id="emailsignup" name="email" required="required" type="email" placeholder="mysupermail@mail.com"/>
                                </p>
                                <p>
                                    <label for="passwordsignup" class="youpasswd" data-icon="p">Your password </label>
                                    <input id="passwordsignup" name="pwd" required="required" type="password" placeholder="eg. X8df!90EO"/>
                                </p>

                                <p class="signin button">
									<input type="submit" value="Sign up"/>
								</p>
                                <p class="change_link">
									Already a member ?
									<a href="#tologin" class="to_register" onclick="changetitletosignin()"> Go and log in </a>
								</p>
                            </form>
                        </div>

                    </div>
                </div>
            </section>
        </div>
           <script>
    function changetitletosignup(){
        document.title='Signup'

    }
    function changetitletosignin() {
        document.title='Signin'
    }



    </script>
    </body>
  
</html>